### ISSUE TITLE
Support additional Gira eNet devices - DVT_JA1M, DVT_SD1M, DVT_SA1Z

### ISSUE THREAD

**Issue by adebree** [mnordseth/enet-homeassistant#1]
Thank you for your work! I've recently installed the custom component into my new bought house with an existing eNet installation, all GIRA components. Many devices are already known and support, but I have three in my setup that aren't. 

Is there anything I can do or provide to get these supported?

The info I get from the debug log is the following typeID's:

`DVT_JA1M` => Blinds actuator, 1-gang Mini - partnr: 5427 00 - https://katalog.gira.de/en/datenblatt.html?id=635930

`DVT_SA1Z` => Switching actuator, 1-gang intermediate plug - partnr: 5448 02 - https://partner.gira.com/nl_NL/service/download/index.html?type=L&id=2956

`DVT_SD1M` => DALI control unit, 1-gang Mini - partnr: 5422 00 - https://katalog.gira.de/en/datenblatt.html?id=635927

I'm more than happy to test (or anything else related to this custom component).

**Comment by mnordseth** [comment]
Hi Arne,

I added the three devices you listed. The switching actuator and DALI unit I expect will just work. Let me know if those work after upgrading the integration.

The blinds actuator is different and currently not supported, as I do not have any blinds at my home.

Can you share the diagnostics output (go to the integrations view, click options on the enet integration and select download diagnostics). That will provide me with information on what functions that device exposes.

**Comment by adebree** [comment]
My setup exposed to HA just went from 21 to 32 devices, awesome :D. Like you expected, the`DVT_SA1Z` and `DVT_SD1M` actuators do work as expected.

I've generated the diagnostics output and since I saw at leas a couple of sensitive details I decided to only share the result of one of the `DVT_JA1M` devices. If you need more info please let me know.

[HomeAssistant-eNet-DVT_JA1M-diagnostics.txt](https://github.com/mnordseth/enet-homeassistant/files/10187057/HomeAssistant-eNet-DVT_JA1M-diagnostics.txt)

**Comment by mnordseth** [comment]
Thanks! The way I understand the device, it exposes two control channels, one that controls the blind height, and one that control the angle.

With the current implementation, the device should show up in Home Assistant as a dimmer that control the blind height. Is that right?

**Comment by adebree** [comment]
That's correct, a `DVT_JA1M` device in HA is now shown as a dimmer with the brightness control being the percentage closed. 0% being completely open, 100% being closed. 

Couple of observations while testing:

- this is probably 'fixed' when the device is exposed to HA as a cover instead of a light: in HA the 'brightness' slider goes only as low as 1% (not 0). The cover will travel to 1% closed, good! But there is no way to get it to 0 / open completely from that 1% state. Toggling the on/off toggle to off doesn't trigger any motion when it's at 1% (and it jumps to back to 'on' after the local poll figures out the actual state of the cover from eNet). When the cover is closed at a higher percentage, like 10%, and then toggling the HA 'light' to off, makes the cover travel to 0. Will evaluate this behaviour again after you will probably change this to a 'cover' (or whatever you think is better)

- because a cover / venetian blind has a travel time, HA fights a bit with the state eNet is reporting. What happens is that when the 'position' is set to for example 20% from HA, the cover does starts moving. But the slider jumps back to the point the cover is at the moment of the local poll taking place. This is 'corrected' after the next poll. But since this seems to be at something around a 10s interval it might take a while and in the mean time shows an incorrect state. I'm not sure how if there is any reasonable fix for this, other than faster polling :(

**Comment by mnordseth** [comment]
That the brightness slider only goes to 1 is a UI 'issue' in Home Assistant. I use the [slider-entity-row](https://github.com/thomasloven/lovelace-slider-entity-row) on some entities, and there you can go to 0.

To me, it looks like the cover entity typically uses a very different UI in Home Assistant, so I am unsure what is most desirable. 

I am currently working on a large change where I subscribe for events from the Enet Server to drive updates of the UI. and I suspect that it will also resolve your second issue. It is in pretty good shape, you can try it from the "events"  branch. I would love to get feedback on that.

**Comment by adebree** [comment]
Hit me up if you want me to validate / test anything related to eNet and Home Assistant.

**Comment by mnordseth** [comment]
I have added initial support for cover entities now. Closing this issue for now. Feel free to reopen if something is off with that support.
