### ISSUE TITLE
Electric shutters and newer eNET essays Series 5492xx or 5493xx

### ISSUE THREAD

**Issue by rphamel** [mnordseth/enet-homeassistant#10]
Hello Magnus,

first of all I would like to thank you for the great work you have put into this integration. I was looking for something usable for the integration of an eNET environment in HA for a long time. 
I have quite a large eNET environment with a lot of actuators and radio attachments and I encountered some peculiarities when implementing your integration. All lamps stored on the eNET server were recognized without errors as devices with their entities. Even those that have a dimmer function. 

In addition, I have a number of outdoor electric shutters that were also recognized. Here I discovered the first anomaly. These were also detected as lamps with "dimming function". In fact, however, the switch works and lets the shutters move to the 100% or 0% position. When using the slider for the dimmer, they also move to intermediate positions. Here a declaration as "shutter" or "roller shutter" would be nice, because the entity would not talk about "brightness" then. However, another conspicuous feature would be of greater importance: GIRA has changed from the 2000 system to the 3000 system over the years. Here also the correct eNET essays for roller shutter controls or dimmers must be bought, since GIRA ensures by attached "plastic clips" that only these can be used. Here exactly I now have the problem that just these essays were not recognized by the integration. All previous essays (old series 5491 xx) worked as described above. The new ones (series 5492 xx and 5493 xx) are all not recognized.

Can this be easily fixed? Interestingly, the mini roller shutter actuators (eNET) have been recognized without any problems (even as dimmed lights).

If I can provide any further input please feel free to contact me, I will be happy to do so. Also I am available for any further tests of integration with my environment.

Many greetings and thanks again for the great work so far!
Rolf

**Comment by mnordseth** [comment]
Hi Rolf,

I have not implemented covers as they are called in home assistant, but chose to have the blinds show up as a light, so that it at least can be controlled from within Home Assistant. You can also change the icon, etc in HA to make it look like a blind.

I will look into having them show up properly when time permits.

For the devices that don't show up, I will need some data to figure out. Can you send me the debug info from the integration? You can go to any enet device and click "Download diagnostics". If you send that to me by email, I will take a look.

**Comment by rphamel** [comment]
Hello Magnus,

I am not shure if my last mail has reached you? I got an error during the send-mail process.

Just let me know if you got the requested diagnostics file.

Regards,
Rolf

**Comment by mnordseth** [comment]
No I didn't get it, so it would be great if you tried again.

**Comment by iMarcusR** [comment]
Hey Magnus, appreciate your great work on eNet! In case you‘re adding better support for covers/window blinds, I‘d be up for testing it, too. Mine are DVT_SJA1 (Centre plate for blinds control). As I want to use them in Homekit, my inner monk is going nuts with them being lights :) Cheers!

**Comment by rphamel** [comment]
Hello Magnus,

after intensive use of v0.94 I notice that the blinds cannot be addressed quite correctly. Coming from a value greater than zero setting to 0% does not lead to a raising (i.e. opening) of the blinds. Here rather a value of 1% must be selected so that something happens. 
I also believe that the current status of all actuators should be queried even better. All actuators must be switched on and off at least once, depending on their status, in order to perform the actual action during the third switching operation. Do you see a possibility to improve this?
A few eNet devices are not yet recognized from my extensive configuration. For example, current measurement actuators such as a motion detector that would also provide values for motion and brightness in addition to the connected device (for example, a spotlight).
I would be happy to hear if you plan to continue working on the integration of these devices as well. However, the current intermediate status is really great for eNet users! Thanks a lot for this great work!
Greetings Rolf

**Comment by iMarcusR** [comment]
Hey Magnus, I've tried the new 0.95b and the covers are integrated much nicer now from my setup. Only the % of open/close seems to be off, but that has been the case in the eNet App, too. I guess it's just passing that problem on. Thanks a lot anyway!

**Comment by mnordseth** [comment]
I just made a small fix on the cover position. Enet represents them as 0-100, while HA is 0-255. So it should be better now.

Do any of you have blinds with tilt control?

**Comment by iMarcusR** [comment]
Amazing! Works a lot better. Thank you! I have classic rolling shutters, not tilting unfortunately. There's still a little "offset", ie "30% open" translates to ~20% openess of the shutter. But I can easily life with that. I guess that offset makes sense as it counts the "dead room" into account that it needs to pull up the shutters, until it actually starts to let light in, if you know what I mean :)

**Comment by webdevsmarthome** [comment]
Hi Magnus, 
great job -writing this integration. 
I'm waiting for that for years and now I love your integration. I have a eNet integration with 31 devices and it is working - not perfect at the moment, but I look forward to further versions with confidence. 
My wish is to implement a better support of louvre (shutter) for setting correct positions and better status support from switches by manual use. 
If you need some for testing, let me know how I can support you. 
Many, many thanks for this Home Assistant Integration! :-) :-) :-)

**Comment by mnordseth** [comment]
I have recently made some updates to how the position of blinds is represented. Can you confirm if that is working for you now?

As to the ability to stop the blind, I can see from the enet api that there is some function for it, but I unfortunately don't know what arguments to supply.

**Comment by ChrisSoelder** [comment]
Hi Magnus,
first of all I want to thank you for your awesome work you have done with this integration. I was also looking forward to something usable to integrate my eNET environment for a long time.
As you mentioned before, you are in need for additional data for the different devices in the eNet ecosystem.
I've got an extensive setup in my home including dimmer (dali, 1-10v, regular), switches, blinds with tilts, light sensor, universal sender for wind sensor etc. If this can be of any help supporting your work, I'm happy to provide what I can.

**Comment by mnordseth** [comment]
Hi Chris, do you have devices that are not supported by the integration?
