### ISSUE TITLE
New eNet Server version 2.4

### ISSUE THREAD

**Issue by nestorix1343** [mnordseth/enet-homeassistant#11]
I received an e-mail about the eNet SMART HOME Server Update 2.4. It will introduce connectivity to the Gira One System (apparently some other domotica system). 

I am wondering if this update would break this current eNet library of enet-homeassistant or not. I am not brave enough to try the update because I do not know if I can downgrade back to my current version.

Anyone any insights into this?

**Comment by webdevsmarthome** [comment]
Hi, I updated already to eNetServer Version 2.4.0 and the home assistant integration is still working fine for me. I'm still really happy for this integration. 

I have just one remark, all switches are integrated as lights, so I have some fan and other things with are in domain light, but should be in domain switch. Is there a workaround or solution?

Great job programming this integration :-)
