### ISSUE TITLE
Blinds show wrong state

### ISSUE THREAD

**Issue by joergpichler** [mnordseth/enet-homeassistant#15]
Hello Magnus,

I have Jung Blinds actuators and they show the wrong state using this integration. When they are fully openend they show up as fully closed. I guess the problem is that [in the code](https://github.com/mnordseth/enet-homeassistant/blob/b8d9fbf8f15b27e6f409ab48b2441a62480e41c8/custom_components/enet/cover.py#L72) 100 is mapped to fully open which is the other way round for my blinds actuators.

I could provide any debug information if needed.

Regards
Jörg

**Comment by mnordseth** [comment]
Hi Jörg,

I do not have any blind actuators in my setup, so any help debugging this would be appreciated.

Can you provide a table where you set the blind from the enet app to Closed, Open and show the corresponding state in Home Assistant?

Thanks,
Magnus

**Comment by joergpichler** [comment]
Heres a quick table I created, the values in Home Assistant are inverted and can even go beyond 100%

|eNet App|Home Assistant|
|--------|--------------|
|0% (open)|	Closed
|15%|216%
|35%|165%
|59%|104%
|83%|43%
|97%|7%
|100% (closed)|Opened

**Comment by mnordseth** [comment]
Thanks!

Can you also test the other way around, ie set it from HA and read the state in the enet app?

**Comment by joergpichler** [comment]
Sure

|Home Assistant|eNet App|Value shown in Home Assistant once it reaches destination|
|----------------|----------|-----------------------------------------------------------|
|Closed|0% (open in reality)|Closed
|83%|68%|81%|
|57%|78%|56%|
|17%|94%|15%|
|Open|100% (closed in reality)|Open|

Also the UI control does not match the physical reality.

![grafik](https://github.com/mnordseth/enet-homeassistant/assets/7032094/59f49046-c15b-4c7e-b1b5-26ad35b20911)
The blind in the control is dragged fully down but it says open? Should be the extact opposite...not sure if this is related to the underlying issue

**Comment by mnordseth** [comment]
I just pushed a new release that I hope should resolve this. Please test it and let me know.

**Comment by mnordseth** [comment]
Great that you have it running with debug. I am very much in the blind here... Did you remember to change the is_open() function as well?

**Comment by joergpichler** [comment]
That fixed the open / closed confusion. Now just the UI still needs to be fixed. Any hints on how to make the blind closed (i.e. fully down) when it's closed and vice versa?
![grafik](https://github.com/mnordseth/enet-homeassistant/assets/7032094/76267f60-5439-42d6-b6ac-02fa4e4bc74c)
![grafik](https://github.com/mnordseth/enet-homeassistant/assets/7032094/2ebe9dc5-a910-44af-b394-5afe221a3a23)

**Comment by mnordseth** [comment]
Great progress! My guess would be that is_open() is what drives the label / text, and that the UI is from the integer value.

**Comment by joergpichler** [comment]
I tinkered with the code a bit and finally found the solution for my shutters / blinds. I really do not know the best english word for german "Rollladen", which is something that rolls down outsied over the windows.

**Comment by mnordseth** [comment]
Thanks for figuring this out. I have merged your pull request and published a new version. Looking at the description of device classes at https://www.home-assistant.io/integrations/cover/  the shade may sound most like what you describe.
