### ISSUE TITLE
Support brightness values of brightness Sensors

### ISSUE THREAD

**Issue by joergpichler** [mnordseth/enet-homeassistant#16]
I have 3 Jung [Brightness Sensors](https://www.jung.de/en/online-catalogue/350780900/). Is it possible to read the Lux values with the integration?

**Comment by mnordseth** [comment]
Yes, that should be possible. Can you provide me with the debug information for your system? Go to integrations, enet and download diagnostics. You can share it directly with me.

**Comment by joergpichler** [comment]
I have just sent you an email. Thanks!

**Comment by mnordseth** [comment]
I just released initial support for the brightness sensor. For now the value is just forwared to HA, unsure if they need to be scaled. I am unable to test this in my setup, so appreciate any feedback.

**Comment by joergpichler** [comment]
I just updated the plugin and the sensor values show the same value as the eNet App
![grafik](https://github.com/mnordseth/enet-homeassistant/assets/7032094/01520722-8efb-4889-8b82-51bd5ffbf377)
I am just wondering why there are these other "Schwellwert" values and how to get rid of them. Also for some reason the naming of this value is broken for one of my three sensors

**Comment by mnordseth** [comment]
Thanks for the feedback. The extra entities ("Schwellwert") are channels that are disabled in enet. I have pushed a new release that filter them out.
