### ISSUE TITLE
Problems with eNet JUNG FM LS 5004 M

### ISSUE THREAD

**Issue by leonidas82** [mnordseth/enet-homeassistant#19]
Hi all, 
thanks for this great work. I'm super new to HomeAssistant and hope you can help me on this.

I use the JUNG FM LS 5004 M - shown in HomeAssistant as "DVT_WS4BJF50CL (Transmitter module F50 CD/LS 4-gang)
von Gira / Jung". When I want to do some automation with them, I only get 4 buttons instead of 8 provided. only the left buttons 1,3,5,7) are shown. Does anyone know what's wrong here? 

Thanks in advance, 
Leo
 
![image](https://github.com/mnordseth/enet-homeassistant/assets/46271190/cc35df06-865f-4f4f-bb3f-e66f82e66b8f)

**Comment by nestorix1343** [comment]
I do not know what you mean exactly with “left” buttons. I think the upper left physical button is button 1 & 2, the upper right physical button is button 3 & 4 and so on.

If a button is directly linked to an actor in the eNet server configuration, you do not get a separate up and down event. 

If a button is available to the eNet app (so you can program it from that app to do things) you do get the separate up and down events.

The 1-way, 2-way and 4-way sensors (buttons) I have show the exact same behavior when directly connected to an actor. I think you can circumvent this by uncoupling the button from the actor and handle it via a scene. However, you lose the slow dim-up and slow dim-down capabilities if you are using a dimmer actor.

**Comment by mnordseth** [comment]
Buttons show up a bit differently depending on if they are configured as a rocker switch or controlling a scene. The code that handles the events will work on all buttons regardless of how they are configured, but not what drives the configuration UI. I have released an update to the integration that should have all buttons show up in the automation configuration.

**Comment by leonidas82** [comment]
> Buttons show up a bit differently depending on if they are configured as a rocker switch or controlling a scene. The code that handles the events will work on all buttons regardless of how they are configured, but not what drives the configuration UI. I have released an update to the integration that should have all buttons show up in the automation configuration.

**Comment by leonidas82** [comment]
wonderful - thanks a lot!
