### ISSUE TITLE
Sensors not showing up in Home Assistant

### ISSUE THREAD

**Issue by Adversio** [mnordseth/enet-homeassistant#20]
Hi! First of all, I want to thank you so much for creating this integration. I have been searching for an integration like this for a long time. This works great! I have one question/feature request, When I look in the integrations I see all the actors, scenes and blinds but the sensors (dimmer/switch buttons, remotes, movement sensors) don't show up. Is there a way to get them showing up in Home Assistant as wel? 

Thank you very much for all the hard work!

Regards,

Mark

**Comment by mnordseth** [comment]
Hi Mark,

What is supported has evolved from what I have in my own installation, and later expanding with things other have, where they have provided debug logs allowing me to work on those. You can send me that information by going to the enet integration in home assistant and selecting "Download diagnostics".

Please note that I have very limited time to work on this at the moment, so I cannot promise to look into it any time soon.

If you have experience developing python, I can give you some pointers on how to dig in yourself.

**Comment by gillmar** [comment]
Hi Magnus,
I'm a new joiner to Home Assitant and your enet integration and I love it and I like to contribute.
Is I have a lot of the Jung Energy Sensors (DVT_ES1Z, DVT_ES4R) and a Steinel sensIQ movement sensor with enet support (brilliant device) and would like to make the functionality also available for others.
If you can give me some pointers, I would be happy to support.

**Comment by Adversio** [comment]
Hi Magnum,

Sorry I didn't respond sooner I guess I missed your reply. In the attachment you can find the diagnostic files. I hope the file reaches you well.


I wish I had any experience in any programming but unfortunately I don't :(

Thanks in advance.

 Regards, 

Mark

[config_entry-enet-761837b60fc2e9693552a8f59423c034.json](https://github.com/user-attachments/files/16735846/config_entry-enet-761837b60fc2e9693552a8f59423c034.json)
