### ISSUE TITLE
Enet integration works beautifully only 1 error message

### ISSUE THREAD

**Issue by Da-Art-76** [mnordseth/enet-homeassistant#21]
Hello Magnus,

I am very grateful to you for the effort you have put into the Enet integration for Home assistant. I am very happy with this.
I have Home Assistant running together with the Homey Pro 2023 and so I can control the whole house.

Everything works 100% I only have this error message in Home Assistant.
Is there something I haven't done right yet?

![Schermafbeelding 2023-12-30 222539](https://github.com/mnordseth/enet-homeassistant/assets/141773897/9fb0e2d7-6498-44d8-8e72-5df798bd72f4)

The error message (in red) says; "setting failed"
Thank you in advance for your response.

Best Regards,
Robert

**Comment by mnordseth** [comment]
Hi Robert,

Thank you for the kind feedback!

Has this error message always been there? Do you find any additional information in the log file?

**Comment by Da-Art-76** [comment]
Hi Magnus,

Thanks for your response, this notification has always been there (from the installation).
In the log I can't find any notifications.

I have a piece of "**Config Entry**" here;

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.12.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Amsterdam",
    "os_name": "Linux",
    "os_version": "6.1.63-haos",
    "supervisor": "2023.12.0",
    "host_os": "Home Assistant OS 11.2",
    "docker_version": "24.0.7",
    "chassis": "embedded",
    "run_as_root": true
    },
    "enet": {
      "version": "0.1",
      "requirements": []
       },
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "google_home": {
      "version": "1.11.0",
      "requirements": [
        "glocaltokens==0.7.0"
      ]
    },
    "dwains_dashboard": {
      "version": "3.6.0",
      "requirements": []
    },
    "homey": {
      "version": "1.1.0",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "enet",
    "name": "Enet Smart Home",
    "config_flow": true,
    "documentation": "https://github.com/mnordseth/enet-homeassistant",
    "issue_tracker": "https://github.com/mnordseth/enet-homeassistant/issues",
    "requirements": [],
    "ssdp": [],
    "zeroconf": [],
    "homekit": {},
    "dependencies": [],
    "version": "0.1",
    "codeowners": [
      "@mnordseth"
    ],
    "iot_class": "local_polling",
    "is_built_in": false
  },
  "data": {
    "config_entry": {
      "entry_id": "41f2314bf5f20ac1360b47af3d68bb6e",
      "version": 1,
      "domain": "enet",
      "title": "Enet Smart Home",
      "data": {
        "url": "http://192.168.xxx.xxx/",
        "username": "xxxxx",
        "password": "xxxxxxxxxxxx"
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "enet_data": [
      {
        "uid": "5e2c69ad-f6dd-431a-b355-f5c2000003ce",
        "typeID": "DVT_SA1M",
        "metaData": {
          "serialNumber": "000a01391715"
        },
        "installationLocationUID": "5e2c69ad-f6dd-431a-b355-f5c20000011d",
        "installationArea": "Veranda",
        "batteryState": null,
        "isModified": false,
        "isSoftwareUpdateAvailable": false,
        "usedLinkResources": 12,
        "securityMode": "SECURE",
        "deviceChannelConfigurationGroups": [
          {
            "no": 0,
            "deviceParameters": [],
            "deviceChannels": [
              {
                "no": 255,
                "channelTypeID": "CT_DEVICE",
                "writeProtected": false,
                "active": true,
                "effectLocationUID": null,
                "effectArea": null,
                "inputDeviceFunctions": [],
                "outputDeviceFunctions": [],
                "deviceParameters": [],
                "deviceChannelDependency": null
