### ISSUE TITLE
Dont work with the gateway

### ISSUE THREAD

**Issue by OMCastle** [mnordseth/enet-homeassistant#22]
Hello,

i have the enet gateway. Is it possible to integrate the connection to the gateway?

Thank. Best regards
Oliver

**Comment by mnordseth** [comment]
Unfortunately. From what I have read, the gateway has a very different API and protocol. Also, I don't own a gateway and have no way of testing it.

**Comment by OMCastle** [comment]
This Adapater for ioBroker works with the gateway. Can you please take al look? Maybe i can test for you?
https://github.com/stoffel7/ioBroker.enet

**Comment by mnordseth** [comment]
I do not have time (or the interest) to implement support for that. I will happily accept pull requests.

**Comment by daNick73** [comment]
@mnordseth just curious: is this something you think even "laymen" maybe able to fix with use of Claude Code?

No guarantee, of course, but is this something you think could be done now easier?

FYI: @OMCastle

**Comment by christiangoetzl** [comment]
The eNet mobile gate IP Gateway is no longer supported as of eNet version 2.0; this implementation for eNet was developed starting with version 2. Therefore, I suspect that this implementation will not work with the old version 1.4 / eNet IP Gateway without major modifications.

**Comment by daNick73** [comment]
What a Pity, my enet Window Shutters are the Main Reason not to go for HA.That said: thx for the fast reply!Von meinem iPhone gesendetAm 07.03.2026 um 13:21 schrieb christiangoetzl ***@***.***>:﻿christiangoetzl left a comment (mnordseth/enet-homeassistant#22)
The eNet mobile gate IP Gateway is no longer supported as of eNet version 2.0; this implementation for eNet was developed starting with version 2. Therefore, I suspect that this implementation will not work with the old version 1.4 / eNet IP Gateway without major modifications.

**Comment by christiangoetzl** [comment]
A used, functional eNet server can now be purchased very cheaply on eBay or similar sites. Get one, connect it to your enet, and upgrade the system to version 2.0 or higher to be able to use this integration 😉

**Comment by daNick73** [comment]
@mnordseth @christiangoetzl  @OMCastle

amazingly, I could create with Claude (and with NO programming skills) a working integration for eNet mobile Gateway, but  EXCLUSIVELY for shutters (since that is my only use cases)

Hope you, @mnordseth , dont mind I attach it here if others come across this (like I did).

Thx for all your efforts!

[enet_gateway.zip](https://github.com/user-attachments/files/25817117/enet_gateway.zip)
