### ISSUE TITLE
enet cannot be found under HACS

### ISSUE THREAD

**Issue by dsl-m** [mnordseth/enet-homeassistant#24]
Unfortunately I cannot find enet-homeassistant as an integration under HACS.  I use HACS version 1.34.0.  The whole thing runs on a Home Assistant green with the latest version.
 I would really like to use it, but unfortunately I can't get any further due to my lack of experience with HA.  Does anyone have any tips on what I can do?

**Comment by adebree** [comment]
@dsl-m did you notice (and try) `enet-homeassistant` install instruction is as a Custom Repository in HACS? 

https://hacs.xyz/docs/faq/custom_repositories/

**Comment by dsl-m** [comment]
I added it manually.  Thanks
