### ISSUE TITLE
Crashing on init

### ISSUE THREAD

**Issue by fierland** [mnordseth/enet-homeassistant#3]
Found that changing line in the Actuator class fixed it, it crashed when adding a disabled channel to a actuator.

from
 if device_channel["channelTypeID"] !=  "CT_DEVICE":
to
 if device_channel["channelTypeID"] not in ( "CT_DEVICE", "CT_DISABLED"):

**Comment by mnordseth** [comment]
Thank you for the notice, I have adopted the fix.
