### ISSUE TITLE
'Device' object has no attribute 'hass_device_entry'

### ISSUE THREAD

**Issue by Scrat-42** [mnordseth/enet-homeassistant#33]
Hello Magnus,
first of all, thank you for the good work.

I am using Gira eNet wireless operating top units (DVT_UP1AV) to control dimming and shading actuators. So everything is working as it should, but when I try to just press and hold the button (long press up or down button) to dim the lights, I get the following error message:

`Logger: custom_components.enet
Quelle: custom_components/enet/__init__.py:122
Integration: Enet Smart Home (Dokumentation, Probleme)
Erstmals aufgetreten: 10:51:06 (10 Vorkommnisse)
Zuletzt protokolliert: 10:51:18`

`Failed to handle event: {'events': [{'sequenceNumber': 9, 'event': 'outputDeviceFunctionCalled', 'eventData': {'deviceUID': '73925705-9a46-4dc2-876c-44d800000695', 'channelNumber': 1, 'deviceFunctionUID': '73925705-9a46-4dc2-876c-44d800000883', 'values': [{'value': 'DOWN_BUTTON', 'valueTypeID': 'VT_ROCKER_STATE'}, {'value': 194, 'valueTypeID': 'VT_ROCKER_SWITCH_TIME'}]}}]} ('Device' object has no attribute 'hass_device_entry')`

`Failed to handle event: {'events': [{'sequenceNumber': 12, 'event': 'outputDeviceFunctionCalled', 'eventData': {'deviceUID': '73925705-9a46-4dc2-876c-44d800000695', 'channelNumber': 1, 'deviceFunctionUID': '73925705-9a46-4dc2-876c-44d800000883', 'values': [{'value': 'UP_BUTTON', 'valueTypeID': 'VT_ROCKER_STATE'}, {'value': 0, 'valueTypeID': 'VT_ROCKER_SWITCH_TIME'}]}}]} ('Device' object has no attribute 'hass_device_entry')`

`Failed to handle event: {'events': [{'sequenceNumber': 13, 'event': 'outputDeviceFunctionCalled', 'eventData': {'deviceUID': '73925705-9a46-4dc2-876c-44d800000695', 'channelNumber': 1, 'deviceFunctionUID': '73925705-9a46-4dc2-876c-44d800000883', 'values': [{'value': 'UP_BUTTON', 'valueTypeID': 'VT_ROCKER_STATE'}, {'value': 384, 'valueTypeID': 'VT_ROCKER_SWITCH_TIME'}]}}]} ('Device' object has no attribute 'hass_device_entry')`

`Failed to handle event: {'events': [{'sequenceNumber': 14, 'event': 'outputDeviceFunctionCalled', 'eventData': {'deviceUID': '73925705-9a46-4dc2-876c-44d800000695', 'channelNumber': 1, 'deviceFunctionUID': '73925705-9a46-4dc2-876c-44d800000883', 'values': [{'value': 'DOWN_BUTTON', 'valueTypeID': 'VT_ROCKER_STATE'}, {'value': 0, 'valueTypeID': 'VT_ROCKER_SWITCH_TIME'}]}}]} ('Device' object has no attribute 'hass_device_entry')`

`Failed to handle event: {'events': [{'sequenceNumber': 17, 'event': 'outputDeviceFunctionCalled', 'eventData': {'deviceUID': '73925705-9a46-4dc2-876c-44d800000695', 'channelNumber': 1, 'deviceFunctionUID': '73925705-9a46-4dc2-876c-44d800000883', 'values': [{'value': 'DOWN_BUTTON', 'valueTypeID': 'VT_ROCKER_STATE'}, {'value': 26, 'valueTypeID': 'VT_ROCKER_SWITCH_TIME'}]}}]} ('Device' object has no attribute 'hass_device_entry')`

`Traceback (most recent call last):
  File "/config/custom_components/enet/__init__.py", line 122, in _async_update_data
    self.handle_event(event)
  File "/config/custom_components/enet/__init__.py", line 167, in handle_event
    "device_id": device.device.hass_device_entry.id,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Device' object has no attribute 'hass_device_entry'`

Do you think you'll have time to implement the object attributes so that I can use them as event triggers for automation?
Jürgen

**Comment by mnordseth** [comment]
Hi Jürgen, I just released an updated version that I believe will solve your issue. Please test it and let me know.
