### ISSUE TITLE
HACS 2.0.0 ready?

### ISSUE THREAD

**Issue by gillmar** [mnordseth/enet-homeassistant#34]
Hi Marius,
I just reviewed the update that HACS 2.0.0 https://github.com/hacs/integration/releases/2.0.0 is out.
Amongst others I found that „The sensor platform has been removed.“

upgrading for enet-issue could be an issue, or?

Regards

Marc

**Comment by gillmar** [comment]
Thx a lot. I will give it try.

**Comment by mnordseth** [comment]
I have upgraded HACS to 2.0 already and it work fine.
