### ISSUE TITLE
first Connection Delay

### ISSUE THREAD

**Issue by lanzlu** [mnordseth/enet-homeassistant#37]
Dear Coder,
I like your Integration....it works really good.
The only thing is, that the first connection need always a longer time to react. After that it is fast. Than after a longer time not using it it needs longer again to react.
Is it possible to fix that?

Thanks for your help.
Regards from switzerland

**Comment by mnordseth** [comment]
I have had this reported once in the past, but I was unable to reproduce it. You can try to run the library from command line to debug further.
