### ISSUE TITLE
integration fails if eNet server has https enabled

### ISSUE THREAD

**Issue by antoonhuiskens** [mnordseth/enet-homeassistant#4]
I'm presuming this is due to the fact that the eNet server presents a self signed cert? fwiw, I'm running over (wired) ethernet and have "HTTPS" enabled in the eNET server interface. Switching to (plain) HTTP followed by just integrating via HACS just works.

**Comment by mnordseth** [comment]
Hi, I just made a new release where that should be resolved. Thanks for letting me know.
