### ISSUE TITLE
Does this provide support for the eNet Mobile Gate from Gira?

### ISSUE THREAD

**Issue by mtoensing** [mnordseth/enet-homeassistant#9]
It looks like this: 
![Gira-eNetMobile-Gate-3](https://user-images.githubusercontent.com/136737/211599270-4166e152-7963-400e-bd2a-d0a072f48001.jpg)

The iobroker adapter https://github.com/SebastianSchultz/ioBroker.enet does support this.

**Comment by mnordseth** [comment]
No, it does not. My understanding is that it has a completely different protocol, so no plans to support it.
